-- Disable RLS on ALL transport tables temporarily to isolate the auth issue
ALTER TABLE transport_vehicles DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_stops DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_students DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_guardians DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_student_guardians DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_trip_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_whatsapp_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_school_closures DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;
